export enum ExerciseSource {
  // Generated deterministically from sentence_tokens (most exercises).
  Spacy = 'spacy',
  // Generated by the ai_exercises stage where deterministic generation is
  // insufficient (e.g. comprehension questions).
  Ai = 'ai',
}
