name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
  pull_request:
    paths:
      - '.github/workflows/docker.yaml'
      - 'Dockerfile'
      - 'pnpm-lock.yaml'

jobs:
  app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.4.0
        with:
          dockerfile: Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: engofy:api
          load: true
          cache-from: type=gha,scope=api
          cache-to: type=gha,mode=max,scope=api

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: engofy:api
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os'
          severity: 'CRITICAL,HIGH'
